spring:
  application:
    name: todo

  config:
    import: optional:file:.env[.properties]

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
