spring:
  application:
    name: todo

  config:
    import: optional:file:.env[.properties]

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: true

  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    properties:
      oracle:
        connect-timeout: 3
        retry-count: 20
        retry-delay: 3
        ssl: true
